### ISSUE TITLE
Cannot add a <span>

### ISSUE THREAD

**Issue by frahugo** [tiff/wysihtml5#106]
We just noticed that we cannot insert a simple span tag with no attributes.  We are using the advanced parsing rules. By looking at the rules, it seems that the span tag is allowed.  We also noticed that is we put a "s" tag, it gets renamed to "span", and it eventually gets deleted. ;-)

The following code in parser.js is responsible for cleaning up the span elements with no attributes.

```
// Cleanup senseless <span> elements
if (cleanUp &&
    newNode.childNodes.length <= 1 &&
    newNode.nodeName.toLowerCase() === DEFAULT_NODE_NAME &&
    !newNode.attributes.length) {
  return newNode.firstChild;
}
```

Is this code really useful?  Removing it allows having a simple "span" tag.

**Comment by tiff** [comment]
wysihtml5 removes the `<span>` because it thinks that it is needless because it only contains one child and also it has no attributes. Imho that is a very smart behavior. Why do you need meaningless span tags in the generated html?

If you want `<s>` tags you just have to adjust your parser rules:
https://github.com/xing/wysihtml5/blob/master/parser_rules/advanced.js#L243

**Comment by frahugo** [comment]
Well, for instance, in a H1 header, we would include a span to apply some CSS to a part of the H1 content.  I suggest that you leave the span in there, although it causes problems in the parsing logic.  Is there any problem of having only one child for the tag?

**Comment by tiff** [comment]
Hi @frahugo,

you can now disable this behavior. Check the commit referenced above.

Cheers!

**Comment by JoseTomasTocino** [comment]
Is this available in the distributable, minified library file? Doesn't seem to work.
