### ISSUE TITLE
Any examples for using Save feature?

### ISSUE THREAD

**Issue by chrisjstevenson** [tiff/wysihtml5#24]

**Comment by tiff** [comment]
Hey Chris, sorry, what save feature are you talking about?

**Comment by chrisjstevenson** [comment]
Hi, I'm trying to figure out how I can save the editor's markup back to some server side code.  I was looking through your examples but the only related content involved [data-wysihtml5-dialog-action="save"], and I'm not sure that's relevant.  

Ideally I'd be looking for a way to trigger an callback function that would allow me to get at the HTML markup that's created when a person formats text in the editor.

**Comment by tiff** [comment]
Hi @chrisjstevenson,

First of all: `[data-wysihtml5-dialog-action="save"]`is not what you are looking for.
It's used for applying the values of a dialog (insertImage, insertLink, ...).

The editor always keeps its corresponding `<textarea>` in sync.
The `<textarea>` will always hold the current generated html markup.
In order to send the html to the server just put your `<textarea>` in a `<form>` and submit it.

If you want to access the current editor value via JS api:

```
var editor = new wysihtml5(...);
var currentValue = editor.getValue(); // there you go!
```

If you need to execute something when the user formatted:

```
editor.on("aftercommand:composer", function() {
    doSomething();
});
```

(make sure to use wysihtml5 0.3 RC1)

Please close this issue if it answered your questions.

**Comment by chrisjstevenson** [comment]
Thanks, will try this

**Comment by AgungNurwedi** [comment]
dfgdfgfdg
![006](https://user-images.githubusercontent.com/15689111/40046136-02b14534-57e1-11e8-9c8e-3fc0d5985698.png)
