### ISSUE TITLE
Context menu triggers undo in Chrome

### ISSUE THREAD

**Issue by w0rm** [tiff/wysihtml5#254]
This happens with the recent build from master branch.

I create images and tables using `composer.commands.exec("insertHTML"` then wysiwyg undoes the last operation after right click.  I'm not sure if this behaviour is triggered by `insertHTML` command or some complex HTML that is being inserted (I insert table with thead and tbody).

**Comment by w0rm** [comment]
I've managed to record the screencast of this strange behaviour: http://cl.ly/2k132r002j0U

Debugging it I found that undo gets triggered in `setInterval` call where `contextmenu` event is observed. I also found that `UNDO_HTML` and `REDO_HTML` don't appear in iframe's document immediately after being inserted neither they do in `setInterval` call (that's why undo is triggered, because element with id `_wysihtml5-undo` doesn't exist).

**Comment by steverandy** [comment]
I can confirm that I have the exact issue on chrome ver 23.

**Comment by magnuky** [comment]
Same issue here! Any workaround found?

**Comment by beshkenadze** [comment]
+1

**Comment by nbudin** [comment]
Here is a workaround I found.  Change the `hasUndoInContextMenu` function to return false always, as follows:

``` javascript
    hasUndoInContextMenu: function() {
      // return isGecko || isChrome || isOpera;
      return false;
    },
```

It's not super great, because wysihtml5 will not get the undo/redo event, and the undo behavior will be a little odd as a result.  But, IMO, it's better than having users lose data they entered when they right-click.

**Comment by edwardmsmith** [comment]
If anybody cares, what @w0rm discovered seems to be caused by the `wysihtml5.INVISIBLE_SPACE` in the `UNDO_HTML` and `REDO_HTML`.

Removing the invisible space seems to fix the issue in Chrome without, as far as I can tell, affecting any other behavior in any other browsers.

I'm not sure the space is necessary, as there is no point at which you're going to try to put the selection INTO the middle of those spans, and I think that's what the invisible space is meant to help with.

So, on lines https://github.com/xing/wysihtml5/blob/56960b31adc37e07797382d8e8b10109f206b19c/src/undo_manager.js#L13-L14

I just have:

```
UNDO_HTML           = '<span id="_wysihtml5-undo" class="_wysihtml5-temp"></span>',
REDO_HTML           = '<span id="_wysihtml5-redo" class="_wysihtml5-temp"></span>',
```

Hope this helps!
