### ISSUE TITLE
Edit input value

### ISSUE THREAD

**Issue by tonyouyang** [tiff/wysihtml5#37]
Is there a way editing the input value i.e. markup saved previously ?

**Comment by tiff** [comment]
Hi @tonyouyang,

sorry I don't really understand what you mean. Can you elaborate?
Thanks!

**Comment by tonyouyang** [comment]
Hi @tiff ,
I intended to revise the content in textarea. I've got it done. Sorry to bother!

**Comment by pkimbrel** [comment]
Can I ask - what was the solution?  I think I'm trying the same thing to no avail.

I want to update the entire value of the text area with a completely new value.  I'm using jQuery:

$("#content").val("this is &lt;b&gt;new&lt;/b&gt; content");

Where "content" is my text area.  I see the text area getting the new value, but the wysihtml5 doesn't update.  Any modification to the wysihtml5 side then reverts my text area.

How does one request the wysihtml5 area to refresh?

**Comment by tonyouyang** [comment]
Hi @pkimbrel . I didn't "refresh". I just set textarea's value before initializing of wysihtml5.

**Comment by tiff** [comment]
Hey @pkimbrel,

try `wysihtml5.Editor.prototype.setValue`.

Example:

``` javascript
myEditor = new wysihtml5.Editor("...");
// ...
myEditor.setValue("<p>foobar</p>", true);
```

**Comment by pkimbrel** [comment]
That did the trick!  Thanks guys!

Another quick question.  I see from the source code that the 2nd parameter of setValue() (the boolean) is "parse".  What is the implication of setting that to false?  I tried it with "false" and it still worked.  I will say, though that I had valid markup.  Is that a safety in case I try to set invalid markup?

**Comment by tiff** [comment]
If the second parameter is true wysihtml5 will run the html through the parser to make sure the html matches the given parser rules before displaying it.

For example if you disabled iframe tags in your parser rules then this html:
`<p>foobar</p><iframe src="http://www.google.de"></iframe>`
will be converted to
`<p>foobar</p>`

It's recommended to always set it to true since the html will anyway be parsed at some time (eg. before the form gets submitted)

**Comment by pkimbrel** [comment]
@tiff Awesome!  Thank you very much.  Love this plug-in!
