### ISSUE TITLE
IE8 Insert Image

### ISSUE THREAD

**Issue by bobanj** [tiff/wysihtml5#58]
When inserting image somewhere inside text, the image is always inserted at the beginning of document.

**Comment by tiff** [comment]
This works for me correctly when using the example editor:
http://tifftiff.de/wysihtml5/examples/advanced.html

Are you trying to insert the image in a different way?

**Comment by bobanj** [comment]
Yes, I use an overlay/modal where the user enters the image url. I do it like this:
editor.fire("unset_placeholder"); // remove placeholder if first thing in the editor is link/image
editor.focus();
editor.composer.commands.exec("insertImage", imageUrl);

**Comment by tiff** [comment]
Ah I see. The problem you are dealing with is a pure IE issue.
This crappy browser loses it's selection whenever you unfocus it.

You can fix that easily:
Before the editor loses focus in order to show the modal window do `var bookmark = editor.composer.selection.getBookmark();`

When the editor receives focus again (after closing the modal window) do:
`editor.composer.selection.setBookmark(bookmark);`

You might also need to set `unselectable="on"` on the button element that triggers the modal window to prevent the editor from losing focus too early (before you capture the bookmark).

Hope this helps.

**Comment by bobanj** [comment]
Than you Christopher :) that is very helpful. :) works like a charm
