### ISSUE TITLE
IE9 opening createLink dialog removes selection 

### ISSUE THREAD

**Issue by qrush** [tiff/wysihtml5#59]
Reproduced this on the advanced demo. Steps:
- Type some text
- Highlight a few words
- Click "Insert link" button
- :bug: Selection disappears
- Fill in URL, hit OK
- Link is attached as expected.

Seems confusing/broken that the editor "forgets" the selection.

**Comment by tiff** [comment]
Yeah this is a well known IE restriction.

It does not only lose the selection visually:
wysihtml5 saves the selection before the "insert link" dialog appears and restores the selection as soon as the insertLink dialog is closed.

There are plenty of articles on the web covering this bug:
http://stackoverflow.com/questions/1470932/ie8-iframe-designmode-loses-selection
http://www.tinymce.com/forum/viewtopic.php?pid=59653
http://code.google.com/p/google-web-toolkit/issues/detail?id=6976

CKEditor and TinyMCE have the same problem.

I'm afraid this can't be fixed.

However you could tackle this with some UI magic:
Show the "insert link" dialog in a modal window on top of the editor.
So that the user doesn't see the text he originally selected. That makes it a bit less confusing (imho).

**Comment by qrush** [comment]
Not going with the modal approach. Friggin' IE. :(

**Comment by tiff** [comment]
I leave this open for a while hoping that someone comes by with an idea on how to deal with this.

**Comment by tiff** [comment]
The commit above doesn't fix this issue. I referenced the wrong issue. Sorry for the confusion.
