### ISSUE TITLE
Trigger click on data-wysihtml5-dialog-action="save"

### ISSUE THREAD

**Issue by ejholmes** [tiff/wysihtml5#60]
What's the proper way to trigger a save on a dialog via JavaScript? I've tried something like:

``` javascript
$('[data-wysihtml5-dialog-action="save"]').trigger('click');
```

But it doesn't cause the dialog to save.

**Comment by tiff** [comment]
That's not working like that since jQuery can't trigger events that itself didn't attach.

You'll need to write your own triggerEvent function (or you just copy the one from QUnit which should work perfectly in all browsers: https://github.com/jquery/qunit/blob/master/qunit/qunit.js#L634).

There's currently no better way to save and close the dialog. Sorry for that.

**Comment by ejholmes** [comment]
Didn't know that. Thanks for the response!
