### ISSUE TITLE
bold and Italic

### ISSUE THREAD

**Issue by MattFielding** [tiff/wysihtml5#67]
Although `<b>` and `<i>` are very much a part of the HTML5 spec they no longer mean 'Bold' and 'Italic'. 
So UI icons representing bold and italic need to use `<strong>` and `<em>`.

`<b>` according to the spec is used to make text “stylistically offset from the normal prose without conveying any extra importance.
`<i>` represents text that’s “in an alternate voice or mood, or otherwise offset from the normal prose” 

this article sums it up well
http://www.impressivewebs.com/bold-italic-html5/

**Comment by pygy** [comment]
[B] and [I] buttons are fixtures in rich text edinting UI. 

They are universally understood, and are actually commonly used in the way the HTML5 spec preconises.

I don't think they should be changed.

**Comment by MattFielding** [comment]
What i'm saying is keep the [b] and [i] buttons on the interface. But make them output `<strong>` and `<em>`.

**Comment by pygy** [comment]
Sorry, I read your message backwards.

**Edit**: that being said, it may be confusing for non-webdevs who take a look at the source...

**Comment by tiff** [comment]
That's an easy change.Will check the spec and change it accordingly. Thank you!

**Comment by pygy** [comment]
The WHATWG was on crack when it came to that consensus. Please keep the `<I>` and `<B>` tags, or perhaps make it an option.

IMO, from a UX perspective,  EM and STRONG don't make sense in this scenario.

**Comment by MattFielding** [comment]
The problem is you can't second guess why a user wants to make something bold. Both sets of elements mean different things and even having an option to use one over the other isn't enough.

The [b] and [i] buttons may be useful in word processing applications where content is being formatted for printing and they certainly are part of a user's mental model, but they really only make sense in a visual medium, and the web isn't just a visual medium anymore, that's why many new elements exist. Do these really buttons have a place anymore in the world wide web?

Maybe we should create a new mental model? :-)

<strong>The challenge:</strong> Could <b>wysihtml5</b> lead the way in throwing out the [b] and [i] buttons altogether?

**Comment by netbyte** [comment]
Is this closed?

**Comment by tiff** [comment]
@netbyte No it isn't!
@MattFielding that sounds innovative. I'm open to any ideas. However creating a new UX pattern that a normal user would not understand isn't an option :)

**Comment by NWSE-ICO** [comment]
@MattFielding, agreed, but unfortunately, UX patterns are quite resistant to changes. Most semantical discussions on WHATWG and elsewere are not of that importance to users who want to emphasize their text with "bold". And they would like to have an option to change the font to Comic Sans btw.

@tiff: suggesting to implement a Configuration for the [b]/[i] button output (default <b> and <i>, optional <strong> and <em>).

**Comment by ForbesLindesay** [comment]
@MattFielding I personally think that although the meaning of them is 'emphasis' and 'in an alternative voice', most websites will still choose to render that as something similar to bold and italics.  Perhaps it should be up to individual web browsers to choose how they want the buttons to look.  e.g. <b>emphasis</b> and <i>quote</i> would be acceptable things to render on the buttons, in the style of the website they're editing on.  But I think in general users will view them as bold and itallics, the point that the WHATWG were getting at, is that it's up to the individual website how exactly they render 'bold', they might render it as making the text blue, rather than making the lines thicker, so the speck reflects that.

**Comment by MattFielding** [comment]
The issue is that we have two sets of elements that in a 'visual' medium you would expect to render the same way, but in a non visual medium, they don't mean the same thing. Picking just one set for your user to use implies the web is just a visual medium, which it clearly is not.

As a starting point, how about this as an idea?

![Bold button](http://f.cl.ly/items/1h1A0o0h2W1d1T3w3p2q/wysihtml5.gif)

**Comment by NWSE-ICO** [comment]
We'd have to remove the tag representation, as many users won't understand them. But then, the choice between "no importance" and "extra importance" will probably irritate the user, since he sees his text in bold anyway, no matter what he tries. If the choice is between a semantically correct markup (the engine understands the user) and a user that is not irritated (the user understands the engine), then I prefer the latter.

**Comment by ForbesLindesay** [comment]
@ingochao I agree, and anyway, when was the last time you used bold when the intended meaning wasn't "This text is more important".  The only other time I use bold is when I'm saying <b>This is what bold text looks like</b>.  Bold is what emphasis looks like, users know the bold means emphasis.  The italics one is more vague, people sometimes use italics to mean emphasis, rather than an alternative voice.

**Comment by tiff** [comment]
Ok, I'd like to stay with `<b>` and `<i>`.

However @MattFielding you can easily change the behavior by using the `formatInline` command.
See https://github.com/xing/wysihtml5/wiki/Supported-Commands#wiki-formatInline

The good thing about wysihtml5 is that anyone can create his own toolbar and use commands as he likes to.

Thanks also to @ingochao, @ForbesLindesay and @pygy for their input. Great discussion!
