### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by elrafael** [tiff/wysihtml5#80]
How about an image upload?

Let me propose a situation:
- A client (with basic almost none knowledge) needs to upload an image from her/him computer to the server. How can I develop a plugin (or anything like that) for that?

With you need some help for PHP developing, I can help you. When I have more free time, I'll fork your project and try to play around, but first I really want to know if there's something already done.

Thanks and 5 stars for your work, keep going :)

**Comment by tiff** [comment]
wysihtml5 should stay a clientside-only library. So there will never be support for an image upload action. But feel free to create a plugin for that. It's pretty easy to insert an image via javascript as soon as you have it's url:

``` javascript
yourEditor.composer.commands.exec("insertImage", "http://foo.com/your_image.jpg");
```

Hope this helps.
Looking forward. Thank you!

**Comment by svallory** [comment]
I vote to reopen since you could do both, stay client-side only and have image uploads, using something like http://api.imgur.com

[NicEdit](http://nicedit.com/) does it.

**Comment by yukulele** [comment]
I think it's possible to use html5 file API to work with <tt>&lt;input type="file"&gt;</tt> client-side only
- Example: http://html5demos.com/file-api-simple
- reference: http://www.w3.org/TR/FileAPI/
- MDN: https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications
- Browser-support: http://caniuse.com/#feat=fileapi
- polyfill: https://github.com/Jahdrien/FileReader

**Comment by MysticEarth** [comment]
@yukulele This will only _read_ the file. For saving it on a server you'll allways need some sort of back-end to handle the file upload.

**Comment by yukulele** [comment]
Yes, but it's the same for <tt>&lt;textarea&gt;</tt> content.

**Comment by kibaekr** [comment]
I also think wysihtml5 has everything it needs to be the number one text editor, but it needs to be able to upload an image... I really wish it was easily possible.

**Comment by r043v** [comment]
an other good tuto for use pictures without any upload [here](http://www.html5rocks.com/en/tutorials/file/dndfiles/).

not use server side save/process is not impossible, an img src attribute can be in data:base64

problem will be if we use multiple times the same picture, for that we can use background-image on css class

second problem will be saving these couples of class/picture, and/or the full sized original pictures in case of resize, this need to be out of html source

we maybe conciderate using local storage for original pictures (this will force to always use the same computer to edit) associated with a dedicated save/load if server side implemented for that (=> not always the same computer)

an other way can be done with saving content as json object instead of plain html, who will contain both html / pictures and why not direct out css (used for blit and not edit), but server side will need a small more work to extract that and display it corectly, for blit and edit case

we need to think about a nice api to allow that.

**Comment by kibaekr** [comment]
Hmm, well I don't mind using server side to save the photos to our database, as long as users can see the image in the text editor upon upload and position the photo as they please.

As a beginner myself, I know it would be extremely helpful if a gem/api/plugin was available for us to follow along and implement the 'local image uploading' feature to wysihtml5 :)

**Comment by gauravvgat** [comment]
Coming back to the topic, I wanted to replace the textbox in  insertImage modal to file upload. I am stuck as to how to replace the control and access the posted file. Any help would be appreciated.

![Capture](https://f.cloud.github.com/assets/2862148/100319/1148d988-6802-11e2-8380-626fc2cdebb0.JPG)

**Comment by lafeber** [comment]
+1 for advanced image functionality. This is _the_ missing element that prevents me from ditching the hopeless ckeditor. http://html5demos.com/file-api-simple would be super nice.

**Comment by coupling** [comment]
It's here.
https://github.com/bassjobsen/wysihtml5-image-upload/
