### ISSUE TITLE
IE(9): error focusing on hidden element

### ISSUE THREAD

**Issue by javan** [tiff/wysihtml5#9]
Hey there, we're exploring using this editor at 37signals, and I ran into a small issue in IE9. Here's an example test case:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
<title>test </title>
  <script src="wysihtml5-0.2.0.js" type="text/javascript"></script>
  <meta charset="utf-8">
</head>

<body>
  <div style="display: none;">
    <textarea id="editor"></textarea>
  </div>
  <script type="text/javascript" charset="utf-8">
    new wysihtml5.Editor("editor", { style: true })
  </script>
</body>
</html>
```

The problem occurs when using `{ style: true }` on a textarea that's hidden. Here's the resulting error in IE:

```
SCRIPT16389: Incorrect function.

wysihtml5-0.2.0.js, line 6887 character 7
```

The problematic code is here:
https://github.com/xing/wysihtml5/blob/master/src/views/composer.style.js#L64-65

The element responds to `setActive`, but calling it results in the error (presumably because the element is hidden). Removing that condition altogether and relying on the more verbose code below works fine. I'd be happy to provide a pull request to do just that, but wanted to check with you first to see if there's other options.

I'm just a day or two into exploring wysihtml5 and so far it's great! Thanks for your work.

**Comment by tiff** [comment]
Looking into it! Thanks for the positive feedback.

**Comment by tiff** [comment]
Hey javan,

I just fixed this by wrapping the setActive() with a try/catch:
https://github.com/xing/wysihtml5/commit/215de8f2cec88b64d5882404e888808715ab9245

The focusWithoutScrolling method is needed in order to retrieve :focus css styles from the textarea to make the actual editor behave similar.

So be aware that hiding the textarea on initial state will cause this to fail in all browsers (that's at least what I assume).

I was thinking about other solutions like making the textarea temporarily visible but that might be a big overhead since I therefore need to figure which parent element of the textarea has a "display: none"...

Ping me if you have a better idea. Thanks!

**Comment by javan** [comment]
Thanks, that seems perfectly fine. I've actually changed my approach and am waiting for elements to become visible before applying the editor, but good to know it won't be an issue if I backtrack.
